listener 18883 127.0.0.1
allow_anonymous true
log_type all
log_dest stderr
require_certificate false
cafile /home/cluster/Important/Projects/C/open-bambu-networking/.fakebroker/cert.pem
certfile /home/cluster/Important/Projects/C/open-bambu-networking/.fakebroker/cert.pem
keyfile /home/cluster/Important/Projects/C/open-bambu-networking/.fakebroker/key.pem
tls_version tlsv1.2
